import pytest
from fixtures.page_fixtures import loc_factory
from factories.location_factory import LocationFactory

@pytest.mark.smoke
@pytest.mark.regression
@pytest.mark.home_page
def test_partial_start_selects_suggestion(home_pg, loc_factory: LocationFactory):
    """
    Positive: Valid partial input in the Starting Point field triggers autocomplete
    and normalizes the value to a full location name.

    Uses LocationFactory for realistic partial/full location pairs.
    The expectation is tied to the randomly chosen partial → full mapping.

    Current behavior:
    - Typing a short prefix shows suggestions
    - Autocomplete normalizes to a full place name
    - Final value contains the city from the selected suggestion

    Steps to reproduce manually:
    1. Open https://roadtrippers.com
    2. In "Starting Point" field type a short prefix (e.g. "Chi" or "New Y")
    3. Wait for suggestions → select the expected city
    4. Field changes from partial to full location

    Expected behavior:
    - Input value changes from partial to full normalized location
    - Final value contains the city that matches the partial input
    - No timeout or crash

    """
    home_pg.navigate()

    # Get one consistent LocationData instance
    loc = loc_factory.build()

    # Use the random partial generated by the factory
    home_pg.enter_start(loc.partial_start)

    final_value = home_pg.get_start_attribute_value().strip()

    # Verify it changed (not partial anymore)
    assert final_value != loc.partial_start.strip(), \
        f"Autocomplete did not update start input (still '{loc.partial_start}')"

    # Extract the expected city from the full start (first part before comma)
    expected_city = loc.start.split(',')[0].strip().lower()

    assert expected_city in final_value.lower(), \
        f"Expected city '{expected_city}' not found in final value '{final_value}'"


# ─────────────────────────────────────────────────────────────


@pytest.mark.smoke
@pytest.mark.regression
@pytest.mark.home_page
def test_partial_destination_selects_suggestion(home_pg, loc_factory: LocationFactory):
    """
    Positive: Valid partial input in the Destination field triggers autocomplete
    and normalizes the value to a full location name.

    Uses LocationFactory for realistic partial/full location pairs.
    Expectation is tied to the randomly chosen partial → full mapping.

    Current behavior:
    - Typing a short prefix shows suggestions
    - Autocomplete normalizes to a full place name
    - Final value contains the city from the selected suggestion

    Steps to reproduce manually:
    1. Open https://roadtrippers.com
    2. In "Destination" field type a short prefix (e.g. "Ca" or "San F")
    3. Wait for suggestions → select the expected city
    4. Field changes from partial to full location

    Expected behavior:
    - Input value changes from partial to full normalized location
    - Final value contains the city that matches the partial input
    - No timeout or crash

    """
    home_pg.navigate()

    loc = loc_factory.build()

    home_pg.enter_destination(loc.partial_dest)

    final_value = home_pg.get_destination_attribute_value().strip()

    # Verify it changed (not partial anymore)
    assert final_value != loc.partial_start.strip(), \
        f"Autocomplete did not update start input (still '{loc.partial_start}')"

    # Extract the expected city from the full start (first part before comma)
    expected_city = loc.destination.split(',')[0].strip().lower()

    assert expected_city in final_value.lower(), \
        f"Expected city '{expected_city}' not found in final value '{final_value}'"


# ─────────────────────────────────────────────────────────────

#===================================
#   Negative Test Cases
#==================================

@pytest.mark.regression
@pytest.mark.negative
@pytest.mark.home_page
def test_empty_fields_prevent_navigation(home_pg):
    """
    Negative: Submitting the search form with both start and destination fields empty
    should prevent navigation to the Trip Planner page.

    Current behavior:
    - Clicking "Plan Your Trip" with empty fields does not load the planner
    - submit_search() returns None (no TripPlannerPage object)
    - Validation errors may appear (red borders/messages) or the form stays active

    Steps to reproduce manually:
    1. Open https://roadtrippers.com
    2. Leave both "Starting Point" and "Destination" fields empty
    3. Click "Plan Your Trip" button
    4. Observe: no redirect to maps.roadtrippers.com, stay on home page
    5. Possible red error messages or highlights around empty fields

    Expected behavior:
    - No navigation to planner occurs (planner is None)
    - Either validation error messages appear OR the search form remains ready/visible
    - No crash or unexpected redirect
    """

    # Step 1: Navigate to home page and ensure overlays are gone
    home_pg.navigate()

    # Step 2: Submit search without filling inputs
    planner = home_pg.submit_search()

    # Step 3: Verify no navigation to maps page occurred
    assert planner is None, \
        "Planner should not load when fields are empty"

    # Step 4: Either validation messages are shown or the search form is still ready
    assert home_pg.has_error_message() or home_pg.is_search_form_ready(), \
        "Expected validation error or no navigation"

# ─────────────────────────────────────────────────────────────

@pytest.mark.regression
@pytest.mark.home_page
@pytest.mark.negative
@pytest.mark.xfail(reason="enter_start() always waits for autocomplete container → times out on invalid input")
def test_no_suggestion_for_gibberish_input(home_pg):
    """
    Negative: Completely nonsensical input should not trigger any suggestion.
    Final value should remain exactly the gibberish string.

    Current behavior (why xfail):
    - enter_start() unconditionally waits for .search__autocomplete.search_autocomplete_from
    - Gibberish produces no suggestions → container never appears → TimeoutException
    - Test crashes before checking final value

    Steps to reproduce current failing behavior manually:
    1. Go to https://roadtrippers.com
    2. In "Starting Point" field type: xzyqwp123!@#
    3. Wait ~10 seconds → no suggestions appear, input stays as typed
    4. (In test: wait_for_element_visibility times out → exception)

    Expected behavior (if fixed):
    - No autocomplete container appears
    - Input value remains "xzyqwp123!@#" exactly
    - No timeout or crash

    """
    home_pg.navigate()

    gibberish = "xzyqwp123!@#"

    home_pg.enter_start(gibberish)

    final_value = home_pg.get_start_attribute_value().strip()

    assert final_value == gibberish, \
        f"Gibberish input '{gibberish}' was unexpectedly normalized to '{final_value}'"

# ─────────────────────────────────────────────────────────────

@pytest.mark.regression
@pytest.mark.home_page
@pytest.mark.negative
@pytest.mark.xfail(reason="enter_start() waits for container that doesn't appear → TimeoutException")
def test_partial_input_without_match_keeps_original(home_pg):
    """
    Negative: Partial input with no matching locations should keep the original value unchanged.

    Current behavior (why xfail):
    - "ZzzxxyyyTown" matches nothing → no container → wait times out

    Steps to reproduce manually:
    1. Go to home page
    2. Type "ZzzxxyyyTown" in start field
    3. No suggestions → field stays as typed

    Expected behavior:
    - Input remains "ZzzxxyyyTown"
    - No crash

    """
    home_pg.navigate()

    unlikely_partial = "ZzzxxyyyTown"

    home_pg.enter_start(unlikely_partial)

    final_value = home_pg.get_start_attribute_value().strip()

    assert final_value == unlikely_partial, \
        f"Non-matching partial '{unlikely_partial}' was changed to '{final_value}'"

# ─────────────────────────────────────────────────────────────

@pytest.mark.regression
@pytest.mark.home_page
@pytest.mark.negative
@pytest.mark.xfail(reason="enter_start() waits for non-existent container → TimeoutException")
def test_special_characters_only_no_autocomplete(home_pg):
    """
    Negative: Input with only special characters should not trigger autocomplete or normalization.

    Current behavior (why xfail):
    - Special chars → no suggestions → container never visible → timeout crash

    Steps to reproduce manually:
    1. Open home page
    2. Type "!@#$%^&*()_+-=[]{}|;':\",./<>?" in start field
    3. No dropdown → value stays as typed

    Expected behavior:
    - Value unchanged
    - No timeout

    """
    home_pg.navigate()

    special = "!@#$%^&*()_+-=[]{}|;':\",./<>?"

    home_pg.enter_start(special)

    final_value = home_pg.get_start_attribute_value().strip()

    assert final_value == special, \
        f"Special characters input changed to '{final_value}'"

# ─────────────────────────────────────────────────────────────

@pytest.mark.regression
@pytest.mark.home_page
@pytest.mark.negative
@pytest.mark.xfail(reason="enter_start() waits for container that never appears → TimeoutException")
def test_whitespace_only_input_remains_unchanged(home_pg):
    """
    Negative: Input consisting only of whitespace should not auto-fill a location.

    Current behavior (why xfail):
    - Whitespace → no suggestions → wait times out

    Steps to reproduce manually:
    1. Go to https://roadtrippers.com
    2. Type multiple spaces/tabs in start field
    3. No suggestions → field stays blank/trimmed

    Expected behavior:
    - Value becomes empty string after trim
    - No crash

    """
    home_pg.navigate()

    spaces = "   \t   "

    home_pg.enter_start(spaces)

    final_value = home_pg.get_start_attribute_value().strip()

    assert final_value == "", \
        f"Whitespace-only input resulted in '{final_value}' instead of empty"

# ─────────────────────────────────────────────────────────────

@pytest.mark.regression
@pytest.mark.home_page
@pytest.mark.negative
@pytest.mark.xfail(reason="enter_start() waits for container → times out even on very long input")
def test_very_long_input_does_not_auto_select(home_pg):
    """
    Negative: Extremely long input should not be auto-completed or truncated unexpectedly.

    Current behavior (why xfail):
    - Long text → no match → container never appears → timeout crash

    Steps to reproduce manually:
    1. Type 250+ chars + " invalid place name" in start field
    2. No suggestions → value stays very long

    Expected behavior:
    - No real city selected
    - Length stays large
    - No crash

    """
    home_pg.navigate()

    long_text = "a" * 250 + " invalid place name"

    home_pg.enter_start(long_text)

    final_value = home_pg.get_start_attribute_value()

    assert "chicago" not in final_value.lower()
    assert "new york" not in final_value.lower()
    assert len(final_value) >= 100, "Very long input was truncated too aggressively"